[build] bump python version to 3.9.13
It seems tricky to use 3.8.9 on M1 based Mac OS, so upgrade to latest 3.9 version (3.10 has proven to introduce some breaking changes in the past, and needs more testing)

The failure that motivates this change happens on CI after switching to M1 based Monterey for building.

```
configure: error: Unexpected output of 'arch' on OSX
make: *** No targets specified and no makefile found.  Stop.
ERROR:  Unable to use Python 3.8.9
```